//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagram
    {
        public string Cname { get; set; }
        public int CFee { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> Status { get; set; }
        public byte[] Technology { get; set; }
    }
}
